create models
40PlusBaddies/birthdayApp pull request #9
Opened 2022-10-12 15:01 UTC by marianaWest

I created three Mongoose schemas: User (copied from Leon's template), BirthdayPerson (the only name that came up), and Gift. Please take a look. Also, I wasn't sure how to add the birthday person's id to the gift schema. Any suggestions?

2022-10-12 15:12 UTC, emtek995 requested changes
The type that mongoose uses for the IDs in the database is ObjectId.
You can use 
birthdayPerson: { type: ObjectId, .......

2022-10-12 15:19 UTC, marianaWest commented
thank you Edward, I'll make the change.

2022-10-14 15:10 UTC, emtek995 commented on models/BirthdayPerson.js
> +  }
giftId: {
    type: String,
    required: true,
  }

2022-10-14 15:59 UTC, emtek995 approved these changes
Looks really good.

2022-10-14 15:59 UTC, merged